version: '3.8'

services:
  bomberman-backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=unityuser
      - DB_PASSWORD=unitypass
      - DB_NAME=unity_db
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs

  db:
    image: mysql:latest
    container_name: unity-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: unity_db
      MYSQL_USER: unityuser
      MYSQL_PASSWORD: unitypass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
